/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jsmod2_script_jni_EmeraldScript */

#ifndef _Included_cn_jsmod2_script_jni_EmeraldScript
#define _Included_cn_jsmod2_script_jni_EmeraldScript
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jsmod2_script_jni_EmeraldScript
 * Method:    parse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_jsmod2_script_jni_EmeraldScript_parse
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
